# Generated by Django 4.2.10 on 2024-02-21 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 2, 21, 12, 55, 56, 483795))),
            ],
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Not set', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Not set', max_length=1000, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('category', models.ManyToManyField(blank=True, null=True, to='appBrowser.category')),
            ],
        ),
    ]
