# Generated by Django 4.2.10 on 2024-02-22 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 12, 42, 25, 490217)),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='file',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
    ]
