# Generated by Django 4.2.23 on 2025-08-28 10:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0002_alter_category_created_at_alter_paperinfo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='doi',
            field=models.CharField(blank=True, default='Not set', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 17, 50, 806622)),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
