# Generated by Django 4.2.23 on 2025-08-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0003_paperinfo_created_at_paperinfo_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinfo',
            name='total_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='total_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 22, 28, 244848)),
        ),
    ]
