# Generated by Django 4.2.23 on 2025-08-28 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBrowser', '0004_paperinfo_total_downloaded_paperinfo_total_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinfo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 28, 38, 163699)),
        ),
    ]
