# Generated by Django 4.2.23 on 2025-08-28 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0005_paperinfo_owner_alter_category_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 8, 28, 12, 40, 18, 96279))),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 12, 40, 18, 96113)),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='appBrowser.tag'),
        ),
    ]
