# Generated by Django 4.2.23 on 2025-08-28 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0006_tag_alter_category_created_at_paperinfo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 12, 58, 44, 8778)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 12, 58, 44, 8886)),
        ),
    ]
