# Generated by Django 4.2.23 on 2025-08-28 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBrowser', '0007_alter_category_created_at_alter_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 14, 55, 45, 595418)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 14, 55, 45, 595513)),
        ),
    ]
