# Generated by Django 4.2.23 on 2025-08-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBrowser', '0007_alter_category_created_at_alter_tag_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_comments', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appBrowser.paperinfo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='appDiscussion.comment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['paper', 'created_at'], name='appDiscussi_paper_i_0413be_idx'), models.Index(fields=['parent', 'created_at'], name='appDiscussi_parent__dcb9f1_idx')],
            },
        ),
    ]
